POST http://localhost:8080/test
Content-Type: application/json

{}

###
GET http://localhost:80/api/item
Accept: application/json

###
GET http://localhost:8080/demo/redis/set/491966732886478848/1231231ajdfasfj
Accept: application/json

###

GET http://localhost:8080/ebook-snapshot/get-statistic
Accept: application/json

###
GET http://localhost:8080/test/testBloom/lcy
Accept: application/json